# Generated by Django 4.0.1 on 2022-01-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_book_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='user_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
